modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="minecraft_overhauled"
version="1.0.0"
displayName="Minecraft_Overhauled"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="ThatThingTwo, MCreator"

[[dependencies.minecraft_overhauled]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




